version: '3.1'
services:
    mongodb:
      image: mongo:4.4.14
      container_name: ecommerce-crawler-db
      volumes:
        - ./:/app
      restart: unless-stopped
      ports:
        - 27017:27017